hayate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('discord/', RedirectView.as_view(url="http://discord.gg/Rcec4yD"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='main_site'),

]

projects/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='projects'),
    path('aktywne/', views.projects_active, name='projects_active'),
    path('zakonczone/', views.projects_completed, name='projects_completed'),
    path('porzucone/', views.projects_abandoned, name='projects_abandoned'),
    path('zlicencjonowane/', views.projects_licensed, name='projects_licensed'),
    path('<slug:slug_name>/', views.project, name='project'),
    path('genre/<slug:slug_name>/', views.projects_for_genre, name='projects_for_genre'),
    path('person/<slug:slug_name>/', views.projects_for_person, name='projects_for_person'),
    path('download/<int:chapter_id>', views.download_chapter, name='download_chapter')
]

projects/models.py
from django.db import models
from users.models import User
from autoslug import AutoSlugField
from django.urls import reverse
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist
import json

class NonHentaiQuerySet(models.QuerySet):
    def active(self):
        return self.filter(state=1)
    def completed(self):
        return self.filter(state=2)
    def abandoned(self):
        return self.filter(state=3)
    def licensed(self):
        return self.filter(state=4)   
class NonHentaiProjectsManager(models.Manager):
    def get_queryset(self):
        return NonHentaiQuerySet(self.model, using=self._db).filter(chapter__state=1, state__gte=1, state__lte=3, title__is_hentai=0).order_by('name').prefetch_related('title__genres', 'title__authors').annotate(number_of_chapters=Count('chapter__id'))
    def active(self):
        return self.get_queryset().active()
    def completed(self):
        return self.get_queryset().completed()
    def abandoned(self):
        return self.get_queryset().abandoned()
    def licensed(self):
        return self.get_queryset().licensed()

class SingleProjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('title').prefetch_related('title__genres', 'title__authors')
    

class Genre(models.Model):
    GENRE_TYPES = (
        (0, "gatunek"),
        (1, "grupa demograficzna"),
        (2, "czasy"),
        (3, "miejsce"),
        (4, "inne")
    )
    id = models.AutoField(primary_key=True)
    genre_type = models.PositiveIntegerField(blank=True, null=True, choices=GENRE_TYPES)
    name = models.CharField(max_length=40, blank=True, null=True)
    slug = AutoSlugField(null=True, default=None, unique=True, populate_from='name')

    class Meta:
        db_table = 'genres'
    def get_absolute_url(self):
         return reverse('projects_for_genre', kwargs={'slug_name': self.slug})
    def __str__(self):
        return self.name
    

class Job(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    hide = models.IntegerField()
    next_job = models.ForeignKey('self', on_delete=models.CASCADE)

    class Meta:
        db_table = 'jobs'
    def __str__(self):
        return self.name


class Person(models.Model):
    BLOOD_TYPES = (
        ('0', "0"),
        ('A', "A"),
        ('B', "B"),
        ('AB', "AB")
    )   
    name = models.CharField(unique=True, max_length=100)
    slug = AutoSlugField(null=True, default=None, unique=True, populate_from='name')
    name_kanji = models.CharField(unique=True, max_length=255, blank=True,null=True)
    birthplace = models.CharField(max_length=50, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    blood_type = models.CharField(max_length=2, blank=True, null=True, choices=BLOOD_TYPES)
    description = models.TextField(blank=True, null=True)
    twitter = models.CharField(blank=True, null=True, max_length=200)

    class Meta:
        db_table = 'people'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('projects_for_person', kwargs={'slug_name': self.slug})

class Title(models.Model):
    STATES_JAPAN = (
        (0, 'Powstaje'),
        (1, 'Zakończona'),
        (2, "Wsztrymana")
    )
    TYPES_LIST = (
        (0, 'manga'),
        (1, 'anime'),
        (2, 'gra'),
        (3, 'light novel')
    )
    id = models.AutoField(primary_key=True)
    name = models.CharField(blank=True, null=True, max_length=255)
    slug = AutoSlugField(null=True, default=None, unique=True, populate_from='name')
    name_pl = models.CharField(blank=True, null=True, max_length=255)
    name_en = models.CharField(blank=True, null=True, max_length=255)
    name_kanji = models.CharField(blank=True, null=True, max_length=255)
    alternative_names = models.CharField(blank=True, null=True, max_length=255)
    type = models.IntegerField(choices=TYPES_LIST)
    is_hentai = models.IntegerField()
    authors = models.ManyToManyField(Person, through='Author')
    description = models.TextField()
    total_volumes = models.SmallIntegerField()
    state_japan = models.IntegerField(choices=STATES_JAPAN)
    genres = models.ManyToManyField(Genre, through="ProjectGenre")
    relations = models.ManyToManyField('self', through="TitleRelate", symmetrical=False, related_name="relation")

    class Meta:
        db_table = 'titles'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('project', kwargs={'slug_name': self.slug})

class Project(models.Model):
    def get_upload_path(instance, filename):
        return f"images/banners/{instance.title.id}.jpg"
    STATE_OF_PROJECT = (
        (0, 'Ukryty'),
        (1, 'Aktywny'),
        (2, 'Zakończony'),
        (3, 'Porzucony'),
        (4, 'Zlicencjonowany'),
        (5, 'Wstrzymany')
    )
    title = models.OneToOneField(Title, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=255)
    slug = AutoSlugField(null=True, default=None, unique=True, populate_from='name')
    chapter_prefix = models.CharField(max_length=25)
    state = models.IntegerField(choices=STATE_OF_PROJECT)
    text_state = models.TextField(blank=True, null=True)
    banner = models.ImageField(null=True, upload_to=get_upload_path)
    objects = models.Manager()
    no_hentai = NonHentaiProjectsManager()
    single_project = SingleProjectManager()
            
    class Meta:
        db_table = 'projects'
    def __str__(self):
        return self.name
    def get_cover(self):
        return f'/media/images/covers/{self.title.id}/1.jpg'
    def get_absolute_url(self):
        return reverse('project', kwargs={'slug_name': self.slug})

class Author(models.Model):
    TYPE_OF_WORK = (
        (0, 'Author'),
        (1, 'Artist'),
        (2, 'Assistant')
    )
    person = models.ForeignKey('Person', on_delete=models.CASCADE)
    title = models.ForeignKey('Title', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    work = models.PositiveSmallIntegerField(choices=TYPE_OF_WORK)

    class Meta:
        db_table = 'authors'

    def __str__(self):
        return self.title.name + ' - ' + self.person.name


class Role(models.Model):
    id = models.AutoField(primary_key=True)
    description = models.TextField()
    job = models.ForeignKey('Job', on_delete=models.CASCADE)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE)

    class Meta:
        db_table = 'roles'
    def __str__(self):
        return self.job.name + '-' + self.project.name + '-' + self.user.name


class Volume(models.Model):
    def get_upload_path(instance, filename):
        return f"images/covers/{instance.project.title.id}/{instance.order_number}.jpg"

    id = models.AutoField(primary_key=True)
    order_number = models.IntegerField()
    number = models.IntegerField()
    specific_name = models.CharField(max_length=30, blank=True, null=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    cover = models.ImageField(null=True, upload_to=get_upload_path)
    class Meta:
        db_table = 'volumes'
    def __str__(self):
        return self.project.slug + " " + str(self.order_number)

class Chapter(models.Model):
    SEND_INFO_TO_BOT = (
        (0, 'Nie wysyłaj'),
        (1, 'Wyślij na discord'),
        (2, "Inne")
    )
    id = models.AutoField(primary_key=True)
    filename = models.CharField(max_length=255, blank=True, null=True)
    title = models.TextField(blank=True, null=False)
    number = models.CharField(max_length=10, blank=True, null=True)
    prefix_title = models.CharField(max_length=20, blank=True, default='')
    order_number = models.SmallIntegerField()
    volume = models.ForeignKey('Volume', on_delete=models.CASCADE)
    active = models.IntegerField(choices=SEND_INFO_TO_BOT)
    state = models.IntegerField()
    date = models.DateField()
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    class Meta:
        db_table = 'chapters'
    def __str__(self):
        return self.project.name + "-" + str(self.number)
    def save(self, *args, **kwargs):
        if(self.active == 1 ):
            data = {
                    "title": self.project.title.name,
                    "volume_name": '',
                    "chapter_volume": self.volume.number,
                    "chapter_prefix": self.prefix_title,
                    "chapter_number": self.number,
                    "chapter_title": self.title,
                    "url": f"http://reader.hayate.eu/{self.project.slug}/{self.volume.order_number}/{self.order_number}/view",
                    "baner": f"http://strona.hayate.eu/media/images/banners/{self.project.title.id}.jpg"
            }
            with open('../../../matsuri/data/chapter.json', 'w', encoding="utf-8") as outfile:
                json.dump(data, outfile, ensure_ascii=False)
        super().save() 
    

class ProjectGenre(models.Model):
    id = models.AutoField(primary_key=True)
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE)
    project = models.ForeignKey('Title', on_delete=models.CASCADE)

    class Meta:
        db_table = 'project_genre'
        unique_together = (('genre', 'project'),)
    def __str__(self):
        return self.project.name + "-" + self.genre.name


class Work(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField(null=True, blank=True)
    chapter = models.ForeignKey('Chapter', on_delete=models.CASCADE)
    job = models.ForeignKey('Job', on_delete=models.CASCADE)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True, blank=True)
    prev_work = models.ForeignKey('self', on_delete=models.CASCADE, editable=False, null=True, blank=True)

    class Meta:
        db_table = 'works'

projects/views.py
import os
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader, RequestContext
from django.db.models import Q, Count, Prefetch
from .models import Project, Genre, Chapter, Volume, Title, Person, Author




def index(request):
    projects = Project.no_hentai.all()
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')
    context = {
        'latests': latests,
        'projects': projects,
        'title': 'Wszystkie projekty'
    }
    return render(request, 'projects/index.html', context)

def projects_active(request):
    projects = Project.no_hentai.active().all()
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')
    context = {
        'latests': latests,
        'projects': projects,
        'title': 'Projekty aktywne'
    }
    return render(request, 'projects/index.html', context)

def projects_completed(request):
    projects = Project.no_hentai.completed().all()
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')
    context = {
        'latests': latests,
        'projects': projects,
        'title': 'Projekty zakończone'
    }
    return render(request, 'projects/index.html', context)

def projects_abandoned(request):
    projects = Project.no_hentai.abandoned().all()
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')
    context = {
        'latests': latests,
        'projects': projects,
        'title': 'Projekty porzucone'
    }
    return render(request, 'projects/index.html', context)

def projects_licensed(request):
    projects = Project.no_hentai.licensed().all()
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')
    context = {
        'latests': latests,
        'projects': projects,
        'title': 'Projekty zlicencjonowane'
    }
    return render(request, 'projects/index.html', context)

def project(request, slug_name):
    current_project = Project.single_project
    current_project = current_project.get(slug=slug_name)    
    volumes = Volume.objects.distinct().filter(project__slug = slug_name, chapter__state=1).order_by('order_number').prefetch_related(Prefetch('chapter_set', queryset=Chapter.objects.filter(state=1).order_by('order_number')))
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')

    context = {
        'latests': latests,
        'project': current_project,
        'title':  current_project.title.name,
        'volumes': volumes
    }
    return render(request, 'projects/project.html', context)

def projects_for_genre(request, slug_name):
    projects = Project.no_hentai.filter(title__genres__slug = slug_name).all()
    genre_name = Genre.objects.get(slug = slug_name).name
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')

    context = {
        'projects': projects,
        'title': 'Projekty z tagiem: ' + genre_name.lower(),
        'latests': latests  
    }
    return render(request, 'projects/index.html', context)

def projects_for_person(request, slug_name):
    projects = Project.no_hentai.filter(title__authors__slug = slug_name).all()
    author_name = Person.objects.get(slug = slug_name).name
    latests = Chapter.objects.filter(project__title__is_hentai = 0, state = 1).all().order_by('-date', '-order_number')[:15].select_related('project', 'project__title').only('title', 'number', 'project__slug', 'project__title__name')

    context = {
        'projects': projects,
        'title':  'Projekty dla autora: ' + author_name,
        'latests': latests
    }
    return render(request, 'projects/index.html', context)

def download_chapter(request, chapter_id):
    data = [chapter_id, request.META.REMOTE_ADDR, request.META.HTTP_REFFERER]
    with open(os.path.join(settings.BASE_DIR, 'projects/log.txt'), 'a') as log_file:
        log_file.write('\n')
        log_file.write(', '.join(data))

    chapter_file = os.path.join(settings.FILES_DIR, chapter_relative_path)
    chapter_relative_path = Chapter.objects.filter(id=chapter_id).first().filename
    if chapter_relative_path[0] == '/':
        chapter_relative_path = chapter_relative_path[1:]
    chapter_filename = os.path.basename(chapter_relative_path)
    path = os.path.join(settings.FILES_DIR, chapter_relative_path)
    chapter_file = open(path, 'rb')
    response = HttpResponse(content=chapter_file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = f'attachment; filename="{chapter_filename}"'
    return response

templates/projects/index.html
{% extends 'base.html' %}
{% block content %}
    <h2 class="headline">{{ title | safe }}</h2>
    <div class="projectsContainer">
    {% for project in projects  %}
        <section class="project">
            <div class="project__cover">
                <a href="{{project.get_absolute_url}}">
                    <img class="cover" src="{{project.get_cover}}" alt="Okładka {{project.title.name}}">
                </a>
                <div class="cover__title inverse"> <a href="{{ project.get_absolute_url }}">{{project.title.name}}</a></div>
            </div>
       
                <section class="project__info">
                    <h3 class="title"><a href="{{project.get_absolute_url}}">{{ project.title.name }}</a></h3>
                    <table class="info">
                        <tr>
                            <td class="info__key">
                                Gatunki:
                            </td>
                            <td class="info__value">
                                {% for genre in project.title.genres.all  %}
                                    <a href="{{ genre.get_absolute_url }}" class="genre">{{ genre.name | safe }}</a>{% if not forloop.last %},{% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td class="info__key">
                                Autor: 
                            </td>
                            <td class="info__value">
                                {% for author in project.title.authors.all  %}
                                    <a href="{{ author.get_absolute_url }}" class="author">{{ author.name | safe }}</a>{% if not forloop.last %},{% endif %}
                                {% endfor %}                                
                            </td>
                        </tr>
                        <tr>
                            <td class="info__key">Rozdziały: </td>
                            <td class="info__value">{{project.number_of_chapters}}</td>
                        </tr>
                        <tr>
                            <td class="info__key">Stan: </td>
                            <td class="info__value">{{project.get_state_display | safe}}</td>
                        </tr>
                    </table>
                </section>                

        </section>
    {% endfor %}
    </div>
{% endblock content %}
    

templates/projects/latest.html
<h2 class="headline">Ostatnie rozdziały</h2>
    <ul class="latest">
{% for latest in latests  %}

        <li class="latest__item">
            <p class="latest__project"><i class="fas fa-book"></i> <a href="{{latest.project.get_absolute_url}}">{{ latest.project.title.name | safe }}</a> {% if latest.number != 0 %}<span class="latest__chapter-number">{{ latest.number }}</span>{%endif%}</p>
            <p class="latest__chapter"><a href="http://reader.hayate.eu/{{latest.project.slug}}/{{latest.volume.order_number}}/{{latest.order_number}}/view"/>{{ latest.title | default:"--" | safe }}</a></p>
        </li>

{% endfor %}
    </ul>

templates/projects/project.html
{% extends 'base.html' %}
{% block content %}
<h2><img src="{{project.banner.url}}" alt=""></h2>
<section class="single">
    <h3 class="title primary-text-color">{{ project.title.name }}</h3>
    <table class="single-info">
        <tr>
            <td class="single-info__key">Gatunki:</td>
            <td class="single-info__value">
                {% for genre in project.title.genres.all %}
                <a href="{{ genre.get_absolute_url }}" class="genre">{{ genre.name | safe }}</a>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td class="single-info__key">Autor:</td>
            <td class="single-info__value">
                {% for author in project.title.authors.all  %}
                    <a href="{{ author.get_absolute_url }}" class="author">{{ author.name | safe }}</a>{% if not forloop.last %},{% endif %}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td class="single-info__key">Ilość tomów:</td>
            <td class="single-info__value">{{project.title.total_volumes}}</td>
        </tr>
        <tr>
            <td class="single-info__key">Stan w japonii:</td>
            <td class="single-info__value">{{project.title.get_state_japan_display}}</td>
        </tr>
        <tr>
            <td class="single-info__key">Stan u nas:</td>
            <td class="single-info__value">{{project.get_state_display | safe}}</td>
        </tr>
        {% for role in project.role_set.all %}
        <tr>
            <td class="single-info__key">{{ role.job.name }}:</td>
            <td class="single-info__value">{{ role.user.name }}</td>
        </tr>
        {% endfor %}
    </table>
    <div class="description">{{project.title.description | safe}}</div>
</section>

{% if project.state < 4 %}
 <section class="volumes">

    {% for volume in volumes %}
    <div class="volume">
        <div class="volume__cover">
            <img src="{{volume.cover.url}}">
        </div>
        <div class="volume__chapters">
            <span class="volume__title"> {% if volume.number > 0 %}Tom {{volume.number}} {% else %} {{volume.specific_name}} {% endif %}</span>
            <table class="chapters">
                {%for chapter in volume.chapter_set.all%}
                <tr>
                    <td class=""><a href="http://reader.hayate.eu/{{chapter.project.slug}}/{{chapter.volume.order_number}}/{{chapter.order_number}}/view">{{chapter.prefix_title}} {% if chapter.number != 0 %}{{chapter.number}}{% endif %}</a><a href="/projects/download/{{chapter.id}}">DL<a/></td>
                    <td class="chapter-title"><a href="http://reader.hayate.eu/{{chapter.project.slug}}/{{chapter.volume.order_number}}/{{chapter.order_number}}/view">{{chapter.title}}</a></td>
                    <td class="chapter-date">{{chapter.date}}</td>
                </tr>
                {%endfor%}
            </table>
        </div>
    </div>
    {% endfor %}
</section>
{% endif %}
{% endblock content %}